name = "oraculum-data-api"
main = "src/index.js"
compatibility_date = "2026-09-17"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "oraculum-data"
database_id = "db13fb9b-26c5-4591-88ab-5f249b1b0089"
